add missing linkage to boost_libs:
consensus/.libs/libbitcoinconsensus_la-merkle.o:merkle.cpp:(.text.startup+0x2f): undefined reference to `boost::system::generic_category()'